@answerController = https://localhost:5001/partyquiz/answer

###

GET {{answerController}}/GetAnswersOfQuestion/1898ea2c-c6f9-47af-9e5d-6fe2f7a3064a

###

POST {{answerController}}/CreateAnswer
Content-Type: application/json

{
    "answerText" : "sqsqq",
    "isCorrect" : false,
    "questionId" : "fac7c290-d489-4906-a0cd-9d9a8878e443"
}

###

PATCH {{answerController}}/UpdateAnswer
Content-Type: application/json

{
    "id" : "2961bd89-46c9-4a29-bfb5-fcc46f81aaeb",
    "answerText" : "eeeeeeeee  eeee  eeee",
    "isCorrect" : true
}

###

DELETE {{answerController}}/DeleteAnswer/cfb8c105-e1f6-432d-b952-2fb91d7033b5