@answerController = https://localhost:5003/partyquiz/answer

###

GET {{answerController}}/GetAnswersOfQuestion/3350b16b-5baf-4966-b470-1131e9dfc21d

###

POST {{answerController}}/CreateAnswer
Content-Type: application/json

{
    "roundId" : "d6fb7e54-5ac2-4ff0-a33b-b2f1bea89a67",
    "answerText" : "bbbbbbb",
    "isCorrect" : false,
    "questionId" : "646ed9eb-bfcd-477a-bb0b-9ce56279a6f4"
}

###

PATCH {{answerController}}/UpdateAnswer
Content-Type: application/json

{
    "id" : "3c9158f9-0a21-4909-b993-c323a84811b5",
    "answerText" : "sssseeee"
}

###

DELETE {{answerController}}/DeleteAnswer/17682034-0d30-46da-9e7b-a838b26cb038