@gameController = https://localhost:5001/partyquiz/game

###

GET {{gameController}}/GetAllGames

###

GET {{gameController}}/GetGameByName/Avengers

###

POST {{gameController}}/CreateGame
Content-Type: application/json

{
    "gameName" : "Mocskos Fidesz"
}

###

PATCH {{gameController}}/UpdateGame
Content-Type: application/json

{
    "id" : "9ddac1bd-4659-402b-8d38-f05e2227ec77",
    "gameName" : "Avengers"
}

###

DELETE {{gameController}}/DeleteGame/ebe179ad-3191-4c27-8274-d7bb3ce1fd25