@gameController = https://localhost:5001/partyquiz/game

###

GET {{gameController}}/GetAllGames

###

GET {{gameController}}/GetGameByName/Avengers

###

POST {{gameController}}/CreateGame
Content-Type: application/json

{
    "gameName" : "Avengers"
}

###

PATCH {{gameController}}/UpdateGame
Content-Type: application/json

{
    "id" : "4f8433ca-592e-4b28-ad32-a433b9b74e6c",
    "gameName" : "Avengers"
}

###

DELETE {{gameController}}/DeleteGame/7bf198eb-cc82-4e3d-86ed-007de6b8b58a