@questionController = https://localhost:5001/partyquiz/question

###

GET {{questionController}}/GetQuestionsOfRound/efb33970-835a-449b-a9c1-d7c1e9751977

###

POST {{questionController}}/CreateQuestion
Content-Type: application/json

{
    "questionNumber" : 2,
    "fullScore" : 4,
    "questionText" : "aaaaaaaaaaaaaaaaaaaaaaaa",
    "roundId" : "9433625d-4eea-4b7d-bc05-52dbca2f272f"
}

###

PATCH {{questionController}}/UpdateQuestion
Content-Type: application/json

{
    "id" : "fac7c290-d489-4906-a0cd-9d9a8878e443",
    "questionNumber" : 1,
    "fullScore" : 3,
    "questionText" : "WarmUpsssssss"
}

###

DELETE {{questionController}}/DeleteQuestion/cbbaaabe-9010-4f24-943f-26b285a3b145