@questionController = https://localhost:5003/partyquiz/question

###

GET {{questionController}}/GetQuestionsOfRound/5079a946-9162-4fff-aa32-1a63f91db8a6

###

POST {{questionController}}/CreateQuestion
Content-Type: application/json

{
    "fullScore" : 2,
    "questionText" : "asztamindenit",
    "roundId" : "d6fb7e54-5ac2-4ff0-a33b-b2f1bea89a67"
}

###

PATCH {{questionController}}/UpdateQuestion
Content-Type: application/json

{
    "id" : "3350b16b-5baf-4966-b470-1131e9dfc21d",
    "fullScore" : 5,
    "questionText" : "xxx"
}

###

DELETE {{questionController}}/DeleteQuestion/5013a4c1-5592-4419-b90c-51a30de4856b