@partyQuizController = https://localhost:5001/partyquiz/round

###

GET {{partyQuizController}}/GetRoundsOfGame/9ddac1bd-4659-402b-8d38-f05e2227ec77

###

POST {{partyQuizController}}/CreateRound
Content-Type: application/json

{
    "roundNumber" : 2,
    "roundName" : "abcd",
    "RoundType" : "ABCD",
    "gameId" : "9ddac1bd-4659-402b-8d38-f05e2227ec77"
}

###

PATCH {{partyQuizController}}/UpdateRound
Content-Type: application/json

{
    "id" : "efb33970-835a-449b-a9c1-d7c1e9751977",
    "roundNumber" : 1,
    "roundName" : "Elokeszites",
    "RoundType" : "WarmUp",
    "gameId" : "9ddac1bd-4659-402b-8d38-f05e2227ec77"
}