@roundController = https://localhost:5001/partyquiz/round

###

GET {{roundController}}/GetRoundsOfGame/9ddac1bd-4659-402b-8d38-f05e2227ec77

###

POST {{roundController}}/CreateRound
Content-Type: application/json

{
    "roundNumber" : 2,
    "roundName" : "abcd",
    "roundType" : "ABCD",
    "gameId" : "9ddac1bd-4659-402b-8d38-f05e2227ec77"
}

###

PATCH {{roundController}}/UpdateRound
Content-Type: application/json

{
    "id" : "efb33970-835a-449b-a9c1-d7c1e9751977",
    "roundNumber" : 1,
    "roundName" : "Elokeszites",
    "roundType" : "WarmUp",
    "gameId" : "9ddac1bd-4659-402b-8d38-f05e2227ec77"
}

###

DELETE {{roundController}}/DeleteRound/3d473cac-22a4-49f7-a525-cc253e6872f7