@roundController = https://localhost:5001/partyquiz/round

###

GET {{roundController}}/GetRoundTypes

###

GET {{roundController}}/GetRoundsOfGame/03c37ef5-6c0c-4d82-9dc3-266029df76f3

###

POST {{roundController}}/CreateRound
Content-Type: application/json

{
    "roundNumber" : 1,
    "roundName" : "sdfdfa",
    "roundType" : "ABCD",
    "gameId" : "03c37ef5-6c0c-4d82-9dc3-266029df76f3"
}

###

PATCH {{roundController}}/UpdateRound
Content-Type: application/json

{
    "id" : "9433625d-4eea-4b7d-bc05-52dbca2f272f",
    "roundNumber" : 1,
    "roundName" : "Elokeszites",
    "roundType" : "WarmUp",
    "gameId" : "4f8433ca-592e-4b28-ad32-a433b9b74e69"
}

###

DELETE {{roundController}}/DeleteRound/76cfe482-7e5b-40de-919b-7fb921bf8b9b